# Generated by Django 4.1.7 on 2023-03-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('duedate', models.DateField()),
                ('status', models.CharField(choices=[('completed', 'completed'), ('pending', 'pending')], max_length=50)),
            ],
        ),
    ]
